"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from typing import cast
from urllib.parse import urlparse

import environ
from django.core.exceptions import ImproperlyConfigured

from plaid_integration.token_encryption import TokenKeyRing

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env(
    DJANGO_PRODUCTION=(bool, False),
    DJANGO_DEBUG=(bool, False),
    DJANGO_ALLOWED_HOSTS=(list, []),
    DJANGO_CSRF_TRUSTED_ORIGINS=(list, []),
    DATABASE_URL=(str, ""),
    PLAID_ENABLED=(bool, False),
    PLAID_ENV=(str, "sandbox"),
    PLAID_CLIENT_ID=(str, ""),
    PLAID_SECRET=(str, ""),
    PLAID_TOKEN_KEYS=(str, ""),
    PLAID_WEBHOOK_INBOX_CAP=(int, 10000),
    PLAID_WEBHOOK_PROCESSED_RETENTION_DAYS=(int, 30),
    GOOGLE_AUTH_ENABLED=(bool, False),
    GOOGLE_CLIENT_ID=(str, ""),
    GOOGLE_CLIENT_SECRET=(str, ""),
    GOOGLE_REDIRECT_URI=(str, ""),
    SESSION_ENGINE=(str, "django.contrib.sessions.backends.db"),
)

environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

PRODUCTION = env("DJANGO_PRODUCTION")
SECRET_KEY = env("DJANGO_SECRET_KEY")
DEBUG = env("DJANGO_DEBUG")
ALLOWED_HOSTS = cast(list[str], env("DJANGO_ALLOWED_HOSTS"))
CSRF_TRUSTED_ORIGINS = cast(list[str], env("DJANGO_CSRF_TRUSTED_ORIGINS"))

# The frontend reads the CSRF cookie and echoes it in the X-CSRFToken header,
# so the cookie must stay readable from JavaScript in every environment.
CSRF_COOKIE_HTTPONLY = False

# Mohr's Google flow stores its one-time state in the platform database
# session so retention is covered without a new OAuth-flow model. Keep the
# database-backed engine (the Django default) and never silently swap it.
SESSION_ENGINE = env("SESSION_ENGINE")

if PRODUCTION:
    if DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_DEBUG must be False when DJANGO_PRODUCTION is enabled."
        )
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "DJANGO_ALLOWED_HOSTS must list every allowed host when "
            "DJANGO_PRODUCTION is enabled."
        )
    if any(host == "*" or host.startswith(".") for host in ALLOWED_HOSTS):
        raise ImproperlyConfigured(
            "DJANGO_ALLOWED_HOSTS entries must be exact hosts and must not "
            "contain '*' or begin with '.' when DJANGO_PRODUCTION is enabled."
        )
    if any(
        not origin.startswith("https://") or "*" in origin
        for origin in CSRF_TRUSTED_ORIGINS
    ):
        raise ImproperlyConfigured(
            "DJANGO_CSRF_TRUSTED_ORIGINS entries must start with 'https://' "
            "and must not contain '*' when DJANGO_PRODUCTION is enabled."
        )
    if not env("DATABASE_URL"):
        raise ImproperlyConfigured(
            "DATABASE_URL is required when DJANGO_PRODUCTION is enabled."
        )


# Google OpenID Connect sign-in (issue #120). Disabled by default: the
# settings import succeeds without any Google credentials. When enabled, the
# import fails closed unless every requirement below is met. Secrets stay
# server-side and are never placed in a response or logged.
GOOGLE_AUTH_ENABLED = env("GOOGLE_AUTH_ENABLED")
GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = env("GOOGLE_REDIRECT_URI")

GOOGLE_CALLBACK_PATH = "/api/auth/google/callback/"

if GOOGLE_AUTH_ENABLED:
    if not GOOGLE_CLIENT_ID.strip():
        raise ImproperlyConfigured(
            "GOOGLE_CLIENT_ID must be non-empty when GOOGLE_AUTH_ENABLED is enabled."
        )
    if not GOOGLE_CLIENT_SECRET.strip():
        raise ImproperlyConfigured(
            "GOOGLE_CLIENT_SECRET must be non-empty when GOOGLE_AUTH_ENABLED is enabled."
        )
    # Reject surrounding whitespace instead of silently validating a stripped
    # copy that the runtime would not use. The configured value is the one
    # sent to Google, so it must be exact.
    if not GOOGLE_REDIRECT_URI or GOOGLE_REDIRECT_URI != GOOGLE_REDIRECT_URI.strip():
        raise ImproperlyConfigured(
            "GOOGLE_REDIRECT_URI must be a non-empty absolute URL with no "
            "surrounding whitespace whose exact path is "
            "/api/auth/google/callback/ when GOOGLE_AUTH_ENABLED is enabled."
        )
    try:
        _google_redirect = urlparse(GOOGLE_REDIRECT_URI)
        _google_port = _google_redirect.port
    except ValueError:
        raise ImproperlyConfigured(
            "GOOGLE_REDIRECT_URI must be a valid absolute URL whose exact path "
            "is /api/auth/google/callback/ when GOOGLE_AUTH_ENABLED is enabled."
        ) from None
    if (
        not _google_redirect.scheme
        or not _google_redirect.netloc
        or _google_redirect.hostname is None
        or _google_redirect.username is not None
        or _google_redirect.password is not None
        or _google_redirect.path != GOOGLE_CALLBACK_PATH
        or _google_redirect.params
        or _google_redirect.query
        or _google_redirect.fragment
        or _google_redirect.netloc.endswith(":")
        or (_google_port is not None and not (0 < _google_port <= 65535))
    ):
        raise ImproperlyConfigured(
            "GOOGLE_REDIRECT_URI must be an absolute URL whose exact path is "
            "/api/auth/google/callback/, with no userinfo, query, or fragment, "
            "when GOOGLE_AUTH_ENABLED is enabled."
        )
    if PRODUCTION:
        if _google_redirect.scheme != "https":
            raise ImproperlyConfigured(
                "GOOGLE_REDIRECT_URI must use https when DJANGO_PRODUCTION is enabled."
            )
        if _google_redirect.hostname not in ALLOWED_HOSTS:
            raise ImproperlyConfigured(
                "GOOGLE_REDIRECT_URI host must be one of DJANGO_ALLOWED_HOSTS when "
                "DJANGO_PRODUCTION is enabled."
            )
    elif _google_redirect.scheme == "http":
        if _google_redirect.hostname not in ("localhost", "127.0.0.1"):
            raise ImproperlyConfigured(
                "GOOGLE_REDIRECT_URI may use http only for localhost or 127.0.0.1 "
                "outside production."
            )
    elif _google_redirect.scheme != "https":
        raise ImproperlyConfigured(
            "GOOGLE_REDIRECT_URI must use https or a localhost http URL."
        )
    if SESSION_ENGINE != "django.contrib.sessions.backends.db":
        raise ImproperlyConfigured(
            "SESSION_ENGINE must be django.contrib.sessions.backends.db when "
            "GOOGLE_AUTH_ENABLED is enabled."
        )


# Plaid Sandbox integration (v0.2). See docs/plaid.md sections 2 and 4.
# Disabled by default: the settings import succeeds without any Plaid
# credentials or token keys. When enabled, the import fails closed unless
# every requirement below is met.

PLAID_ENABLED = env("PLAID_ENABLED")
PLAID_ENV = env("PLAID_ENV")
PLAID_CLIENT_ID = env("PLAID_CLIENT_ID")
PLAID_SECRET = env("PLAID_SECRET")

if PLAID_ENABLED:
    if PLAID_ENV != "sandbox":
        raise ImproperlyConfigured(
            "PLAID_ENV must be exactly 'sandbox' when PLAID_ENABLED is "
            "enabled. Production Plaid access is not supported in v0.2."
        )
    if not PLAID_CLIENT_ID or not PLAID_CLIENT_ID.strip():
        raise ImproperlyConfigured(
            "PLAID_CLIENT_ID must be non-empty when PLAID_ENABLED is enabled."
        )
    if not PLAID_SECRET or not PLAID_SECRET.strip():
        raise ImproperlyConfigured(
            "PLAID_SECRET must be non-empty when PLAID_ENABLED is enabled."
        )
    PLAID_TOKEN_RING = TokenKeyRing.from_config(env("PLAID_TOKEN_KEYS"))
else:
    PLAID_TOKEN_RING = None


# Bounded webhook inbox tuning (docs/plaid.md sections 4 and 8): non-secret
# operational constants that fail closed at import so a misconfigured
# deployment never runs with an unbounded inbox or a nonsensical retention
# window. Zero, negative, and non-integer values are rejected.


def _positive_integer_setting(name, default):
    try:
        value = env(name, default=default)
    except ValueError:
        raise ImproperlyConfigured(f"{name} must be a positive integer.") from None
    if value < 1:
        raise ImproperlyConfigured(f"{name} must be a positive integer.")
    return value


PLAID_WEBHOOK_INBOX_CAP = _positive_integer_setting("PLAID_WEBHOOK_INBOX_CAP", 10000)
PLAID_WEBHOOK_PROCESSED_RETENTION_DAYS = _positive_integer_setting(
    "PLAID_WEBHOOK_PROCESSED_RETENTION_DAYS", 30
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "axes",
    "users.apps.UsersConfig",
    "accounts.apps.AccountsConfig",
    "categories.apps.CategoriesConfig",
    "transactions.apps.TransactionsConfig",
    "budgets.apps.BudgetsConfig",
    "dashboard.apps.DashboardConfig",
    "plaid_integration.apps.PlaidIntegrationConfig",
]

AUTH_USER_MODEL = "users.User"
CSRF_FAILURE_VIEW = "config.views.csrf_failure"

# Login abuse protection (issue #79). Five failed credentials in the rolling
# 15-minute window lock out the username + client IP pair; a different
# username or source IP is unaffected and a successful login clears the
# pair's failures. See users/authentication.py for trusted client IP
# resolution and the DRF JSON lockout response.
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_USE_ATTEMPT_EXPIRATION = True
# Both the admin form and API pass the email as Django's `username` credential.
AXES_USERNAME_FORM_FIELD = "username"
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
AXES_RESET_ON_SUCCESS = True
AXES_DISABLE_ACCESS_LOG = True
AXES_CLIENT_IP_CALLABLE = "users.authentication.get_client_ip"
AXES_HTTP_RESPONSE_CODE = 429

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("users.authentication.SessionAuthentication",),
    # Dedicated per-source-IP rate for the public webhook receiver only; no
    # default throttle class is registered, so unrelated APIs are unaffected.
    "DEFAULT_THROTTLE_RATES": {
        "plaid_webhook": "60/min",
        # Only the public Google start endpoint uses this scope; a normal
        # browser performs one start per sign-in or link attempt.
        "google_start": "60/min",
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Handle lockout responses after authentication and session middleware.
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if PRODUCTION:
    database_config = env.db("DATABASE_URL")
    if database_config["ENGINE"] != "django.db.backends.postgresql":
        raise ImproperlyConfigured(
            "DATABASE_URL must point to a PostgreSQL database when "
            "DJANGO_PRODUCTION is enabled."
        )
    if database_config.get("OPTIONS", {}).get("sslmode") != "require":
        raise ImproperlyConfigured(
            "DATABASE_URL must include sslmode=require when "
            "DJANGO_PRODUCTION is enabled."
        )
    # Persistent connections live on the database alias, not as top-level
    # settings. A small pool suits the single Render web instance.
    database_config["CONN_MAX_AGE"] = 60
    database_config["CONN_HEALTH_CHECKS"] = True
elif env("DATABASE_URL"):
    database_config = env.db("DATABASE_URL")
else:
    database_config = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST"),
        "PORT": env("POSTGRES_PORT"),
    }

DATABASES = {"default": database_config}

if PRODUCTION:
    # Render terminates TLS, so trust its X-Forwarded-Proto header and make
    # Django enforce HTTPS and secure cookies itself.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    # Render's health check must not depend on a redirect, and this endpoint
    # exposes only {"status": "ok"}.
    SECURE_REDIRECT_EXEMPT = [r"^api/health/$"]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Short initial HSTS window while the deployment settles in.
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Absolute so the SPA works at nested routes such as /accounts.
STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

# The compiled React app is copied here at image build time. Local development
# and CI have no frontend build, so only include it when it exists.
FRONTEND_DIST_DIR = BASE_DIR / "frontend_dist"
if FRONTEND_DIST_DIR.is_dir():
    STATICFILES_DIRS = [FRONTEND_DIST_DIR]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Vite already content-hashes filenames; manifest rewriting would
        # risk failing the build on Vite output.
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Local and test environments may not have a compiled static root; production
# must scan the real collected directory instead.
WHITENOISE_AUTOREFRESH = not PRODUCTION

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
