# Generated by Django 5.2.17 on 2026-09-11 23:41

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=20,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("category_type__in", ["income", "expense"])
                        ),
                        name="categories_category_type_valid",
                    ),
                    models.UniqueConstraint(
                        models.F("user"),
                        django.db.models.functions.text.Lower(
                            django.db.models.functions.text.Trim(models.F("name"))
                        ),
                        models.F("category_type"),
                        name="categories_user_name_type_unique",
                    ),
                ],
            },
        ),
    ]
