# Generated by Django 5.2.17 on 2026-09-16 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaidConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=100)),
                ("access_token_encrypted", models.TextField(blank=True, null=True)),
                (
                    "encryption_key_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("institution_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("updating", "Updating"),
                            ("error", "Error"),
                            ("revoked", "Revoked"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("sync_cursor", models.TextField(blank=True, null=True)),
                (
                    "transactions_update_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_ready", "Not ready"),
                            ("initial_update_complete", "Initial update complete"),
                            (
                                "historical_update_complete",
                                "Historical update complete",
                            ),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("sync_due", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plaid_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="PlaidAccountLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plaid_account_id", models.CharField(max_length=100)),
                ("plaid_type", models.CharField(max_length=50)),
                ("plaid_subtype", models.CharField(max_length=50)),
                ("mask", models.CharField(max_length=4)),
                (
                    "anchor_provider_current_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("anchor_applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_current_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "provider_available_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="plaid_account_links",
                        to="accounts.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plaid_account_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_links",
                        to="plaid_integration.plaidconnection",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="PlaidWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webhook_type", models.CharField(max_length=50)),
                ("webhook_code", models.CharField(max_length=50)),
                ("item_id", models.CharField(max_length=100)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("initial_update_complete", models.BooleanField(default=False)),
                ("historical_update_complete", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="plaid_integration.plaidconnection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plaid_webhook_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-received_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="plaidconnection",
            index=models.Index(
                fields=["encryption_key_id"], name="plaid_conn_key_id_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="plaidconnection",
            constraint=models.UniqueConstraint(
                fields=("item_id",), name="plaid_connection_item_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="plaidconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["active", "updating", "error", "revoked", "disconnected"],
                    )
                ),
                name="plaid_connection_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="plaidconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("transactions_update_status__isnull", True),
                    (
                        "transactions_update_status__in",
                        [
                            "not_ready",
                            "initial_update_complete",
                            "historical_update_complete",
                        ],
                    ),
                    _connector="OR",
                ),
                name="plaid_connection_transactions_update_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="plaidaccountlink",
            constraint=models.UniqueConstraint(
                fields=("connection", "plaid_account_id"),
                name="plaid_account_link_connection_plaid_account_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="plaidaccountlink",
            constraint=models.UniqueConstraint(
                fields=("user", "account"),
                name="plaid_account_link_user_account_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="plaidwebhookevent",
            constraint=models.UniqueConstraint(
                fields=("idempotency_key",),
                name="plaid_webhook_event_idempotency_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="plaidwebhookevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("connection__isnull", True), ("user__isnull", True)),
                    models.Q(("connection__isnull", False), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="plaid_webhook_event_connection_user_null_pair",
            ),
        ),
    ]
