# Generated by Django 5.2.17 on 2026-09-17 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plaid_integration", "0002_plaidexchangehandle"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaidItemRemovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token_encrypted", models.TextField()),
                ("encryption_key_id", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("failed", "Failed")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_removal_request",
                        to="plaid_integration.plaidconnection",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="plaid_removal_status_retry_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("pending", "failed"))),
                        name="plaid_item_removal_request_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempts__gte", 0)),
                        name="plaid_item_removal_request_attempts_non_negative",
                    ),
                ],
            },
        ),
    ]
