# Generated by Django 5.2.17 on 2026-09-16 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("categories", "0001_initial"),
        ("plaid_integration", "0001_initial"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category_customized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="transactions",
                to="plaid_integration.plaidconnection",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_provider_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_superseded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="note_customized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="plaid_pending_transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="plaid_transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="provider_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="transaction",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("plaid", "Plaid")],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="superseded_rows",
                to="transactions.transaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["manual", "plaid"])),
                name="transactions_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source", "manual"), _negated=True),
                    models.Q(
                        ("connection__isnull", True),
                        ("plaid_transaction_id__isnull", True),
                        ("plaid_pending_transaction_id__isnull", True),
                        ("is_pending", False),
                        ("is_provider_removed", False),
                        ("is_superseded", False),
                        ("superseded_by__isnull", True),
                        ("category_customized", False),
                        ("note_customized", False),
                        ("provider_name", ""),
                    ),
                    _connector="OR",
                ),
                name="transactions_manual_row_no_provider_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source", "plaid"), _negated=True),
                    models.Q(
                        ("connection__isnull", False),
                        ("plaid_transaction_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="transactions_plaid_row_requires_provider_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_superseded", True), ("superseded_by__isnull", False)),
                    models.Q(("is_superseded", False), ("superseded_by__isnull", True)),
                    _connector="OR",
                ),
                name="transactions_superseded_requires_superseded_by",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plaid_transaction_id__isnull", False)),
                fields=("user", "plaid_transaction_id"),
                name="transactions_user_plaid_transaction_id_unique",
            ),
        ),
    ]
