# Generated by Django 5.2.17 on 2026-09-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_transaction_category_customized_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_transfer",
            field=models.BooleanField(default=False),
        ),
    ]
